title: UC TronSoc Wiki
author: Sam Hogan
email: uctronsoc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UC TronSoc Wiki for the Mechantronics Club at the University of Canterbury
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  UCTronSoc # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
